### ISSUE TITLE
feature(Tutorial 1): End-to-End Multibranch Pipeline Project Creation

### ISSUE THREAD

**Issue by ash-sxn** [ash-sxn/GSoC-2023-docker-based-quickstart#38]
- For discussion to replicate Tutorial [End-to-End Multibranch Pipeline Project Creation](https://www.jenkins.io/doc/tutorials/build-a-multibranch-pipeline-project/)
- This tutorial has a Blueocean section, which we can replace with [Pipeline graph view plugin](https://plugins.jenkins.io/pipeline-graph-view/)
- Uses  docker in docker 
- Pinging mentors @berviantoleo @gounthar @jmMeessen

**Comment by jmMeessen** [comment]
Any idea on the strategy you are going to use to move ahead to provide this feature ?
If stuck, I can give you a few hints on how explore this.

Please provide your ideas to start the discussion.

**Comment by jmMeessen** [comment]
I have looked at the tutorial. Although we need to discuss this together, I believe that we should pause working on this because of the heavy dependency on Blue Ocean as a pipeline editor. 

As we are setting up the tooling and testing the concepts, I suggest that we concentrate on being able to support the Maven tutorial (#39 )

For references the source code of the documentation is located at https://github.com/jenkins-infra/jenkins.io/blob/master/content/doc/tutorials/build-a-java-app-with-maven.adoc. The rendered page (with the setup instructions we want to get rid of) is located at https://www.jenkins.io/doc/tutorials/build-a-java-app-with-maven/

**Comment by gounthar** [comment]
This one will need a lot of investigation.
At this stage, I can't tell yet if we can do without `dind` or not (I do hope so, but I haven't tried).
We don't know either if the GraphView Pipeline Plugin is advanced enough to replicate the existing tutorial using BlueOcean.

I would love to have a clear idea of what is possible at the end of the week.
Having a working tutorial would be a nice bonus, though, even if it is a reduced version of the existing tutorial.
