### ISSUE TITLE
feature(Tutorial 2): Build a Java app with Maven  

### ISSUE THREAD

**Issue by ash-sxn** [ash-sxn/GSoC-2023-docker-based-quickstart#39]
- For discussion to replicate Tutorial [Build a Java app with Maven](https://www.jenkins.io/doc/tutorials/build-a-java-app-with-maven/)
- Uses  docker in docker 
- Pinging mentors @berviantoleo @gounthar @jmMeessen

**Comment by jmMeessen** [comment]
For references the source code of the documentation is located at https://github.com/jenkins-infra/jenkins.io/blob/master/content/doc/tutorials/build-a-java-app-with-maven.adoc. The rendered page (with the setup instructions we want to get rid of) is located at https://www.jenkins.io/doc/tutorials/build-a-java-app-with-maven/

**Comment by jmMeessen** [comment]
Brainstorm preparation (suggestion)

- create a summary of the tutorial's step. Each step is described as a single sentence (if needed with the source line number to find the full details)
- evaluate what is the tooling required to perform the step
- is the action useful for the first user's experience? 
   - YES =>  can it be done with the current quickstart setup? Otherwise add the required pre-requisite.
   - NO => must be part of the quickstart automated configuration
- Write the target/ideal flow of user interactions to perform the tutorial (aim validate that nothing was forgotten and that it is usable)
-  List the tooling and setup automation items required to perform the ideal tutorial flow.

**Comment by ash-sxn** [comment]
### Fork and clone the sample repository
- Useful for the first user's experience? Not so much 

@gounthar's script from #52 does this nicely 
### Create your Pipeline project in Jenkins
- Useful for the first user's experience? Yes

for this part Instead of the locally cloned repo(`/home/GitHub/simple-java-maven-app`) we can use users forked repo so that we can build the project on the agent(with custom image)  
### Create your initial Pipeline as a Jenkinsfile
- Useful for the first user's experience? Yes

for this one user will create a `Jenkinsfile` with this 
```
pipeline {
    agent {
        label 'docker-ssh-jenkins-agent'
    }
    stages {
        
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
        
    }
}
```
in the `simple-java-maven-app` as currently done in the tutorial, but instead of just commit user will also push the changes to his forked repo and build the project with 2 steps 
### Add a test stage to your Pipeline
- Useful for the first user's experience? Yes

this will be similar to the above step user will edit `Jenkinsfile` with  Test  stage  and push the changes and then build with 3 steps  
### Add a final deliver stage to your Pipeline
- Useful for the first user's experience? Yes

the Same process can be repeated from above

**Comment by gounthar** [comment]
@ash-sxn, I have resolved the issue regarding the requirement of the full path for `mvn`.

```
ENV M2_HOME="/opt/maven"
ENV PATH="${M2_HOME}/bin/:${PATH}"
RUN echo "PATH=${PATH}" >> /etc/environment
```
