### ISSUE TITLE
Named volumes

### ISSUE THREAD

**Issue by gounthar** [ash-sxn/GSoC-2023-docker-based-quickstart#55]
This is linked to #49 .
What about the volumes? Should we keep them or remove them?

Should we have a separate volume for each tutorial, or use the same volume across all tutorials with a tear-down command to clean it up?

To complete the first milestone, we need a tear-down command that deletes the volume locally (not mandatory when using GitPod).

Once done, we can close this issue and assign it to a future milestone to allow time for discussion on the implementation approach.

**Comment by berviantoleo** [comment]
Both implementations have advantages and disadvantages.

Due to centralize command/script, I expect that the volume is only one.

| | Advantage | Disadvantage |
|--|:--:|:--:|
| Same Volume | We only need to manage one volume and simple | We need to ensure the previous volume before starting any tutorials. |
| Separate Volume | We don't need to wait until the other tutorial is finished before starting a tutorial. | 1. We need to manage multiple volumes that might increase the complexity. 2. Users might have a concern when having multiple volumes. | 

I suggest going with the same volume when start implementing #49. We will consider multiple volumes as the next feature. What do you think?

**Comment by gounthar** [comment]
I agree with you, @berviantoleo. We should stick with the same volume while ensuring it is cleaned up before the start-up and during the teardown.

**Comment by gounthar** [comment]
To clean up the Docker volume before launching `docker-compose up --build` and after `docker-compose down`, we could use the following bash commands:

`docker-compose down -v`

The `-v` option is used to remove the associated volumes along with the containers. This command will stop and remove any running containers defined in the `docker-compose.yml` file, as well as remove the Jenkins Home volume (`jenkins_home`).

We could also maybe use `docker volume rm jenkins_home`. This command will remove the specified Docker volume.

**Comment by ash-sxn** [comment]
This one is solved by the jenkins_teardown.sh right now, right? 
since, It removes the  containers with `docker compose down --volume`
should I close this Issue?

**Comment by gounthar** [comment]
I think so, you can close. 👍
